name: CI deploy

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout DBeaver
        uses: actions/checkout@v2
        with:
          repository: dbeaver/dbeaver
          path: dbeaver

      - name: Build DBeaver
        working-directory: dbeaver/
        run: mvn clean install

      - name: Checkout OrbisRCP
        uses: actions/checkout@v2
        with:
          repository: orbisgis/orbisrcp
          ref: p2-repository

      # Configure git user in order to sign release with OrbisGIS user.
      - name: Configure Git User
        run: |
          git config user.email "info@orbisgis.org"
          git config user.name OrbisGIS

      - name: Clone and build OrbisRCP repo
        run: |
          git clone https://github.com/orbisgis/orbisrcp
          cd orbisrcp
          
          git clone https://github.com/GroovyLanguageServer/groovy-language-server
          cd groovy-language-server
          ./gradlew build
          cd ..
          ls plugins/dependencies
          mkdir  plugins/dependencies/libs
          cp groovy-language-server/build/libs/groovy-language-server-all.jar ./plugins/dependencies/libs/groovy-language-server.jar

          mvn clean install -Dmaven.test.skip=true
          cd ..
          unzip -o -qq orbisrcp/p2/target/p2-1.0.0-SNAPSHOT.zip -d ./
          rm -r orbisrcp

      - name: Push P2 branch
        run: |
          git add *
          git commit -a -m "Update P2 repo."
          git push origin p2-repository
