name: CI build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout DBeaver
        uses: actions/checkout@v2
        with:
          repository: dbeaver/dbeaver
          path: dbeaver

      - name: Build DBeaver
        working-directory: dbeaver/
        run: mvn clean install

      - name: Checkout OrbisRCP
        uses: actions/checkout@v2
        with:
          repository: orbisgis/orbisrcp

      - name: Build OrbisRCP
        run: |
          git clone https://github.com/GroovyLanguageServer/groovy-language-server
          cd groovy-language-server
          ./gradlew build
          cd ..
          ls plugins/dependencies
          mkdir  plugins/dependencies/libs
          cp groovy-language-server/build/libs/groovy-language-server-all.jar ./plugins/dependencies/libs/groovy-language-server.jar
          mvn clean install
